# Dockerfile for company_scrape.py
FROM python:3.9-slim

WORKDIR /app

COPY company_scrape.py requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "company_scrape.py"]